# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release_x86_64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release_x86_64)
  GLFW_config = release_x86_64
  GLEW_config = release_x86_64
  yaml_cpp_config = release_x86_64
  curl_lib_config = release_x86_64
  zlib_config = release_x86_64
  Geometria_config = release_x86_64
endif
ifeq ($(config),release_x86)
  GLFW_config = release_x86
  GLEW_config = release_x86
  yaml_cpp_config = release_x86
  curl_lib_config = release_x86
  zlib_config = release_x86
  Geometria_config = release_x86
endif

PROJECTS := GLFW GLEW yaml-cpp curl-lib zlib Geometria

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Libraries/GLFW -f Makefile config=$(GLFW_config)
endif

GLEW:
ifneq (,$(GLEW_config))
	@echo "==== Building GLEW ($(GLEW_config)) ===="
	@${MAKE} --no-print-directory -C Libraries/GLEW -f Makefile config=$(GLEW_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Libraries/YAMLCPP -f Makefile config=$(yaml_cpp_config)
endif

curl-lib:
ifneq (,$(curl_lib_config))
	@echo "==== Building curl-lib ($(curl_lib_config)) ===="
	@${MAKE} --no-print-directory -C Libraries/CURL -f Makefile config=$(curl_lib_config)
endif

zlib:
ifneq (,$(zlib_config))
	@echo "==== Building zlib ($(zlib_config)) ===="
	@${MAKE} --no-print-directory -C Libraries/ZLIB -f Makefile config=$(zlib_config)
endif

Geometria: GLFW GLEW yaml-cpp zlib
ifneq (,$(Geometria_config))
	@echo "==== Building Geometria ($(Geometria_config)) ===="
	@${MAKE} --no-print-directory -C Geometria -f Makefile config=$(Geometria_config)
endif

clean:
	@${MAKE} --no-print-directory -C Libraries/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Libraries/GLEW -f Makefile clean
	@${MAKE} --no-print-directory -C Libraries/YAMLCPP -f Makefile clean
	@${MAKE} --no-print-directory -C Libraries/CURL -f Makefile clean
	@${MAKE} --no-print-directory -C Libraries/ZLIB -f Makefile clean
	@${MAKE} --no-print-directory -C Geometria -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release_x86_64"
	@echo "  release_x86"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   GLEW"
	@echo "   yaml-cpp"
	@echo "   curl-lib"
	@echo "   zlib"
	@echo "   Geometria"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"